In [31]:
import numpy as np
iou_threshold = 0.5
scores = [0.9, 0.8, 0.7, 0.6, 0.5]
table = np.array([
    np.array([0.9, 0.0, 0.0, 0.0]),
    np.array([0.0, 0.7, 0.0, 0.0]),
    np.array([0.0, 0.0, 0.8, 0.0]),
    np.array([0.0, 0.0, 0.0, 0.6]),
    np.array([0.0, 0.9, 0.0, 0.0])
])
tables = [
    np.array([
        np.array([0.9, 0.0, 0.0, 0.0]),
        np.array([0.0, 0.7, 0.0, 0.0]),
        np.array([0.0, 0.0, 0.8, 0.0]),
        np.array([0.0, 0.0, 0.0, 0.6]),
        np.array([0.0, 0.9, 0.0, 0.0])
    ]),
    np.array([
        np.array([0.0, 0.6, 0.0, 0.4]),
        np.array([0.0, 0.7, 0.2, 0.0]),
        np.array([0.6, 0.0, 0.8, 0.0]),
        np.array([0.0, 0.8, 0.0, 0.6]),
        np.array([0.7, 0.1, 0.0, 0.0])
    ]),
    np.array([
        np.array([0.1, 0.2, 0.3, 0.4]),
        np.array([0.4, 0.3, 0.2, 0.1]),
        np.array([0.3, 0.1, 0.0, 0.0]),
        np.array([0.0, 0.8, 0.0, 0.1]),
        np.array([0.0, 0.0, 0.1, 0.1])
    ]),
    np.array([
        np.array([0.4, 0.6, 0.0, 0.1]),
        np.array([0.0, 0.7, 0.6, 0.0]),
        np.array([0.0, 0.9, 0.8, 0.0]),
        np.array([0.0, 0.8, 0.0, 0.7]),
        np.array([0.6, 0.7, 0.0, 0.0])
    ])
]

for table in tables:
    for score_threshold in scores:
        table_copy = np.zeros(table.shape)
        for i, score in enumerate(scores):
            if score >= score_threshold:
                table_copy[i] = table[i]

        num_tp = 0
        num_fp = 0
        num_fn = 0
        for i, score in enumerate(scores):
            if score >= score_threshold:
                row = table_copy[i]
                max_iou = max(row)
                max_column_index = np.argmax(row)
                column = table_copy[:,max_column_index]
                max_row_index = np.argmax(column)
                if max_row_index == i:
                    num_tp += 1
                else:
                    num_fp += 1
                num_fp += (np.count_nonzero(row) - 1)
            #if score < score_threshold:
            #    row = table[i]
            #    num_fp += np.count_nonzero(row)
        num_fn = 4 - num_tp
        print(score_threshold, num_tp, num_fp, num_fn)
        prec = num_tp / (num_tp + num_fp)
        rec = num_tp / (num_tp + num_fn)
        print(rec, prec)
    print('')

0.9 1 0 3
0.25 1.0
0.8 2 0 2
0.5 1.0
0.7 3 0 1
0.75 1.0
0.6 4 0 0
1.0 1.0
0.5 4 1 0
1.0 0.8

0.9 1 1 3
0.25 0.5
0.8 1 3 3
0.25 0.25
0.7 2 4 2
0.5 0.3333333333333333
0.6 2 6 2
0.5 0.25
0.5 3 7 1
0.75 0.3

0.9 1 3 3
0.25 0.25
0.8 2 6 2
0.5 0.25
0.7 2 8 2
0.5 0.2
0.6 3 9 1
0.75 0.25
0.5 3 11 1
0.75 0.21428571428571427

0.9 1 2 3
0.25 0.3333333333333333
0.8 1 4 3
0.25 0.2
0.7 1 6 3
0.25 0.14285714285714285
0.6 1 8 3
0.25 0.1111111111111111
0.5 1 10 3
0.25 0.09090909090909091



In [29]:
import numpy as np


def calc_ap(recs, precs):
    print(recs, precs)


iou_thresholds = [0.9, 0.8, 0.7, 0.6, 0.5]
scores = [0.9, 0.8, 0.7, 0.6, 0.5]
table = np.array([
    np.array([0.9, 0.0, 0.0, 0.0]),
    np.array([0.0, 0.7, 0.0, 0.0]),
    np.array([0.0, 0.0, 0.8, 0.0]),
    np.array([0.0, 0.0, 0.0, 0.6]),
    np.array([0.0, 0.9, 0.0, 0.0])
])
tables = [
    np.array([
        np.array([0.9, 0.0, 0.0, 0.0]),
        np.array([0.0, 0.7, 0.0, 0.0]),
        np.array([0.0, 0.0, 0.8, 0.0]),
        np.array([0.0, 0.0, 0.0, 0.6]),
        np.array([0.0, 0.9, 0.0, 0.0])
    ]),
    np.array([
        np.array([0.0, 0.6, 0.0, 0.4]),
        np.array([0.0, 0.7, 0.2, 0.0]),
        np.array([0.6, 0.0, 0.8, 0.0]),
        np.array([0.0, 0.8, 0.0, 0.6]),
        np.array([0.7, 0.1, 0.0, 0.0])
    ]),
    np.array([
        np.array([0.1, 0.2, 0.3, 0.4]),
        np.array([0.4, 0.3, 0.2, 0.1]),
        np.array([0.3, 0.1, 0.0, 0.0]),
        np.array([0.0, 0.8, 0.0, 0.1]),
        np.array([0.0, 0.0, 0.1, 0.1])
    ]),
    np.array([
        np.array([0.4, 0.6, 0.0, 0.1]),
        np.array([0.0, 0.7, 0.6, 0.0]),
        np.array([0.0, 0.9, 0.8, 0.0]),
        np.array([0.0, 0.8, 0.0, 0.7]),
        np.array([0.6, 0.7, 0.0, 0.0])
    ])
]

for table in tables:
    precs = []
    recs = []
    for iou_threshold in iou_thresholds:
        num_tp = 0
        num_fp = 0
        num_fn = 0
        for i, score in enumerate(scores):
            row = table[i]
            max_iou = max(row)
            if max_iou >= iou_threshold:
                max_column_index = np.argmax(row)
                print(max_column_index)
                column = table[:,max_column_index]
                print(column)
                is_tp = True
                for j, entry in enumerate(column):
                    if entry >= iou_threshold:
                        if scores[j] > scores[i]:
                            is_tp = False
                if is_tp:
                    num_tp += 1
                else:
                    num_fp += 1
            else:
                num_fp += 1
            num_fp += (np.count_nonzero(row) - 1)
        num_fn = 4 - num_tp
        #print(score_threshold, num_tp, num_fp, num_fn)
        prec = num_tp / (num_tp + num_fp)
        rec = num_tp / (num_tp + num_fn)
        #print(rec, prec)
        precs.append(prec)
        recs.append(rec)
    calc_ap(recs, precs)

0
[0.9 0.  0.  0.  0. ]
1
[0.  0.7 0.  0.  0.9]
0
[0.9 0.  0.  0.  0. ]
2
[0.  0.  0.8 0.  0. ]
1
[0.  0.7 0.  0.  0.9]
0
[0.9 0.  0.  0.  0. ]
1
[0.  0.7 0.  0.  0.9]
2
[0.  0.  0.8 0.  0. ]
1
[0.  0.7 0.  0.  0.9]
0
[0.9 0.  0.  0.  0. ]
1
[0.  0.7 0.  0.  0.9]
2
[0.  0.  0.8 0.  0. ]
3
[0.  0.  0.  0.6 0. ]
1
[0.  0.7 0.  0.  0.9]
0
[0.9 0.  0.  0.  0. ]
1
[0.  0.7 0.  0.  0.9]
2
[0.  0.  0.8 0.  0. ]
3
[0.  0.  0.  0.6 0. ]
1
[0.  0.7 0.  0.  0.9]
[0.5, 0.75, 0.75, 1.0, 1.0] [0.4, 0.6, 0.6, 0.8, 0.8]
2
[0.  0.2 0.8 0.  0. ]
1
[0.6 0.7 0.  0.8 0.1]
1
[0.6 0.7 0.  0.8 0.1]
2
[0.  0.2 0.8 0.  0. ]
1
[0.6 0.7 0.  0.8 0.1]
0
[0.  0.  0.6 0.  0.7]
1
[0.6 0.7 0.  0.8 0.1]
1
[0.6 0.7 0.  0.8 0.1]
2
[0.  0.2 0.8 0.  0. ]
1
[0.6 0.7 0.  0.8 0.1]
0
[0.  0.  0.6 0.  0.7]
1
[0.6 0.7 0.  0.8 0.1]
1
[0.6 0.7 0.  0.8 0.1]
2
[0.  0.2 0.8 0.  0. ]
1
[0.6 0.7 0.  0.8 0.1]
0
[0.  0.  0.6 0.  0.7]
[0.0, 0.5, 0.75, 0.5, 0.5] [0.0, 0.2, 0.3, 0.2, 0.2]
1
[0.2 0.3 0.1 0.8 0. ]
1
[0.2 0.3 0.1 0.8 0. ]
1
[0.